version: '3.9'

services:
  perroute-backoffice-api:
    container_name: tales-tree-rest-api
    build:
      context: ..
      dockerfile: crates/rest/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - '8080:8080'
    env_file:
      - ../.env
      - ../.env.docker
    depends_on:
      - tales_tree_postgres
      - tales_tree_neo4j
