version: '3.9'
services:
  tales_tree_postgres:
    container_name: tales_tree_neo4j
    image: neo4j:latest
    restart: always
    env_file:
      - ../.env.docker
    ports:
      - "7474:7474"
      - "7687:7687"
